---
# Project information
site_name: CPP lab HPC guide
repo_name: cpp-lln-lab/CPP_HPC
repo_url: https://github.com/cpp-lln-lab/CPP_HPC
# docs_dir: alternative_path # docs/ is the default folder
copyright: MIT

# This will use Material them
theme:
  name: material
  language: en
  palette:
    primary: light blue
    accent: light blue
  features:
  - navigation.expand

docs_dir: doc

# Pages
nav:
- Welcome and FAQ: index.md
- HPC UCLouvain (CECI):
  - overview: overview.md
  - cluster code snippets: cluster_code_snippets.md
  - install datalad on the cluster: install_datalad.md
  - run fmriprep: run_fmriprep.md
  - run mriqc: run_mriqc.md
  - run bids-HCPpipelines: run_bids-hcpipelines.md
- Contributing: contributing.md
- Archive:
  - fmriprep cluster workshop (2023):
    - meeting notes: archive/fmriprep_cluster_workshop_2023/joint_meeting_notes.md
    - Compute Canada: archive/fmriprep_cluster_workshop_2023/canada_connect_cluster.md
  - rookie experience (2019): archive/rookie_experience_2019.md
  - fmriprep notes: archive/running_fmriprep.md


# list of extension
markdown_extensions:
- admonition
- pymdownx.details
- toc:
    anchorlink: true
    permalink: '#'
- pymdownx.tasklist:
    custom_checkbox: true

plugins:
- include-markdown
