---
# Project information
site_name: CPP lab HPC guide
repo_name: cpp-lln-lab/CPP_HPC
repo_url: https://github.com/cpp-lln-lab/CPP_HPC

copyright: MIT

# This will use Material them
theme:
  name: material
  language: en
  palette:
    primary: light blue
    accent: light blue

docs_dir: doc

# Pages
nav:
- Welcome: welcome.md
- HPC UCLouvain (CECI):
  - overview: overview.md
  - cluster code snippets: cluster_code_snippets.md
  - run fmriprep: run_fmriprep.md
  - running fmriprep: running_fmriprep.md
  - rookie experience (2019): rookie_experience_2019.md
- fmriprep cluster workshop (2023): 
  - meeting notes: fmriprep_cluster_workshop_2023/joint_meeting_notes.md
  - Compute Canada: fmriprep_cluster_workshop_2023/canada_connect_cluster.md
- Contributing: contributing.md

# list of extension
markdown_extensions:
- admonition
- pymdownx.details
- toc:
    anchorlink: true
    permalink: '#'
- pymdownx.tasklist:
    custom_checkbox: true

plugins:
- include-markdown
